### ISSUE TITLE
Nothing showing up!

### ISSUE THREAD

**Issue by egotham** [JeroenDeDauw/GitHub#10]
I'm newbie with mediawiki but trying to get up working documentation platform for our EU-project. I just downloaded your github extension for mediawiki and I'm able to confirm through "Special:Version" that it's successfully installed on my wiki. However while I try to get something showing up like: {{#github:index.php}} and $egGitHubDefaultRepo = 'egotham/egotham-Ylivieska';   nothing showing up... What I'm missing?

- Jani

**Comment by JeroenDeDauw** [comment]
Sorry for the late reply. Is this still an issue with the latest version of the extension?

**Comment by JeroenDeDauw** [comment]
Assuming this is fixed in 1.0.1.
