### ISSUE TITLE
Uncommitted DB writes (transaction from DatabaseBase::query (MessageBlobStore::clear))

### ISSUE THREAD

**Issue by SevenWarlordsOfTheSea** [JeroenDeDauw/GitHub#14]
Hi,
I have MW 1.22.6 and SMW 1.9.1, when I try to change the language, I get this error:

[f87cf4a3] /mediawiki/index.php/Main_Page Exception from line 316 of C:\xampp\apps\mediawiki\htdocs\includes\MagicWord.php: Error: invalid magic word 'github'

Backtrace:

0 C:\xampp\apps\mediawiki\htdocs\includes\MagicWord.php(239): MagicWord->load(string)
1 C:\xampp\apps\mediawiki\htdocs\includes\parser\Parser.php(4982): MagicWord::get(string)
2 C:\xampp\apps\mediawiki\htdocs\vendor\mediawiki\parser-hooks\src\ParserHooks\HookRegistrant.php(48): Parser->setFunctionHook(string, Closure, integer)
3 C:\xampp\apps\mediawiki\htdocs\vendor\jeroen-de-dauw\mediawiki-github\src\GitHub\Setup.php(75): ParserHooks\HookRegistrant->registerFunction(ParserHooks\FunctionRunner)
4 [internal function]: GitHub\Setup->GitHub{closure}(Parser)
5 C:\xampp\apps\mediawiki\htdocs\includes\Hooks.php(199): call_user_func_array(Closure, array)
6 C:\xampp\apps\mediawiki\htdocs\includes\GlobalFunctions.php(3877): Hooks::run(string, array)
7 C:\xampp\apps\mediawiki\htdocs\includes\parser\Parser.php(275): wfRunHooks(string, array)
8 [internal function]: Parser->firstCallInit()
9 C:\xampp\apps\mediawiki\htdocs\includes\StubObject.php(99): call_user_func_array(array, array)
10 C:\xampp\apps\mediawiki\htdocs\includes\StubObject.php(119): StubObject->_call(string, array)
11 C:\xampp\apps\mediawiki\htdocs\includes\cache\MessageCache.php(996): StubObject->__call(string, array)
12 C:\xampp\apps\mediawiki\htdocs\includes\cache\MessageCache.php(996): StubObject->firstCallInit()
13 C:\xampp\apps\mediawiki\htdocs\includes\cache\MessageCache.php(974): MessageCache->getParser()
14 C:\xampp\apps\mediawiki\htdocs\includes\Message.php(854): MessageCache->transform(string, boolean, Language, Title)
15 C:\xampp\apps\mediawiki\htdocs\includes\Message.php(592): Message->transformText(string)
16 C:\xampp\apps\mediawiki\htdocs\includes\Message.php(649): Message->toString()
17 C:\xampp\apps\mediawiki\htdocs\includes\OutputPage.php(851): Message->text()
18 C:\xampp\apps\mediawiki\htdocs\includes\OutputPage.php(894): OutputPage->setHTMLTitle(Message)
19 C:\xampp\apps\mediawiki\htdocs\includes\Article.php(555): OutputPage->setPageTitle(string)
20 C:\xampp\apps\mediawiki\htdocs\includes\actions\ViewAction.php(44): Article->view()
21 C:\xampp\apps\mediawiki\htdocs\includes\Wiki.php(448): ViewAction->show()
22 C:\xampp\apps\mediawiki\htdocs\includes\Wiki.php(312): MediaWiki->performAction(Article, Title)
23 C:\xampp\apps\mediawiki\htdocs\includes\Wiki.php(602): MediaWiki->performRequest()
24 C:\xampp\apps\mediawiki\htdocs\includes\Wiki.php(467): MediaWiki->main()
25 C:\xampp\apps\mediawiki\htdocs\index.php(49): MediaWiki->run()
26 {main}

The only languages that work without giving problems are English and Spanish... How can I fix this?

I installed the Github Extension by composer, following the instructions, without any problem. I also tried to remove all extensions from Localettings.php, but the problem still occurs...

**Comment by JeroenDeDauw** [comment]
@kghbln @siebrand Any idea?

**Comment by kghbln** [comment]
This extension does not use the new MW 1.23 json system however this should not be an issue in the environment stated. I do not see the problem right now which may very well not come as a surprise.

**Comment by JeroenDeDauw** [comment]
Please reopen if this is still an issue with the latest version
