### ISSUE TITLE
Fatal Exception on mediawiki 1.24.1

### ISSUE THREAD

**Issue by acacha** [JeroenDeDauw/GitHub#15]
Also a warning:

 Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.

Solved with:

 $ sudo php composer.phar remove jeroen-de-dauw/mediawiki-github

**Comment by mwjames** [comment]
@kghbln Seems we hit the same spot, now that smw.org is running 1.24.1, release notes [0] aren't displayed anymore.

[0] https://semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.0

**Comment by JeroenDeDauw** [comment]
@mwjames I think that's quite disjoint. The issue you point to was present before the upgrade. I'm thinking the stuff is getting cached without a TTL and thus staying in the DB forever. We had this before the previous release as well, and then it showed up when we switched to the file with version number in it.

**Comment by JeroenDeDauw** [comment]
@acacha can you provide the actual error you are running into? Saying you fix it by uninstalling the extension is not helpful.

**Comment by JeroenDeDauw** [comment]
I just tried running this extension on MW 1.21 and did not encounter any errors. Please reopen with a more detailed error message if you still have your problem.
