### ISSUE TITLE
Migrate i18n to json

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/GitHub#18]
I can do this i believe. Will do a pull request, soon.

**Comment by JeroenDeDauw** [comment]
\o/

I've also requested a WMF repo to be created, so we can get TWN support: https://www.mediawiki.org/wiki/Git/New_repositories/Requests

**Comment by JeroenDeDauw** [comment]
https://gerrit.wikimedia.org/r/#/c/186223/

**Comment by kghbln** [comment]
Cool!
