### ISSUE TITLE
Support rendering of tables

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/GitHub#19]
Example: https://semantic-mediawiki.org/wiki/User:Jeroen_De_Dauw/Table_markdown_render

Source: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by kghbln** [comment]
Yeah, this is a very important enhancement. I just switch to use [GitHub for the compat overview](https://semantic-mediawiki.org/wiki/Compatibility). It is ok but ... :)

**Comment by skierpage** [comment]
Is this fixed? On 2015-10-15 kghbln [changed](https://semantic-mediawiki.org/w/index.php?title=Help%3ACompatibility&diff=41238&oldid=38364) the [smw.org Compatibility](https://semantic-mediawiki.org/wiki/Compatibility) page to use `{{#github:docs/COMPATIBILITY.md}}` and the tables seem to render OK.

**Comment by kghbln** [comment]
No styling visible to me and thus on the bring of uselessness. So no from my point of view.

**Comment by JeroenDeDauw** [comment]
Indeed, this has not been implemented yet. Behaviour is still as it was when I created this issue.
