### ISSUE TITLE
Allow `$egGitHubDefaultRepo` to hold multiple repos

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/GitHub#29]
I think it will be nice to allow the `$egGitHubDefaultRepo` to hold multiple repos. I believe there are valid usecases to where one would like to embed from more that one repo.

**Comment by JeroenDeDauw** [comment]
I'm not sure I understand... if you want to embed from multiple repos, you can just use the parser function multiple times with a different repo parameter no?

**Comment by kghbln** [comment]
> The parser function does not support multiple repos in a single call, so a default with multiple makes little sense.

Ah, for some reason I figured that the repo needs to be configured, i.e. whitelisted to be usable for the parser function. So I can just add files from other repos too!?

**Comment by kghbln** [comment]
Great, yeah, cool. No I understand the magic. All in fluff now! :D
