### ISSUE TITLE
Convert to PHP 5.4+ short array syntax

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/GitHub#36]
I would have issued a pull request however the convert script fails because "invalid" syntax. Probably they mean something like [L50](https://github.com/JeroenDeDauw/GitHub/blob/master/src/SyntaxRenderer.php#L50)

**Comment by JeroenDeDauw** [comment]
Did you use a recent version of the tool?

Anyway, this is a small extension, and no one is really bothered by the stuff, so don't spend too much time on it.

**Comment by kghbln** [comment]
Yes, but I think it failed on line I quoted. So this is done? No?

**Comment by JeroenDeDauw** [comment]
The line you indicated is valid syntax and is unrelated to `array()` => `[]`

**Comment by kghbln** [comment]
Looks like it. :)

**Comment by JeroenDeDauw** [comment]
Done in https://github.com/JeroenDeDauw/GitHub/pull/40
