### ISSUE TITLE
Formatting is broken with 

### ISSUE THREAD

**Issue by mwjames** [JeroenDeDauw/GitHub#42]
* GitHub	1.4.0 alpha (d484e5d) 18:34, 23 June 2017

## Issue

As observed in https://www.semantic-mediawiki.org/wiki/Help:Integration_tests:

- Formatting of pre elements are broken 
- Formatting of \` attributed text is broken

See the difference in https://www.semantic-mediawiki.org/wiki/Help:Integration_tests vs. https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/README.md

**Comment by JeroenDeDauw** [comment]
Probably this is the new HTML purification stripping out whatever tags where used for this. So likely need some small modification to https://github.com/JeroenDeDauw/GitHub/blob/master/src/ContentPurifier.php
