### ISSUE TITLE
Is gitlab supported by this plugin ?

### ISSUE THREAD

**Issue by cavepopo** [JeroenDeDauw/GitHub#51]
Hi,

I am very new to mediawiki and was wondering if this plugin would allow one to use hosted gitlab in place of github ?
The goal is to be able to display the build status icons on a wikimedia page...

I can't get it to work, here is the repo path:
`https://l-gitlab1.lab.rms.loc/salt/salt_states_COMMON/commits/dev`

I tried several ways but none of them works:
```
{{#github:https://l-gitlab1.lab.rms.loc/salt/salt_states_COMMON/badges/dev/pipeline.svg}}
{{#github:salt/salt_states_COMMON/badges/dev/pipeline.svg}}
{{#github:pipeline.svg|salt_states_COMMON|dev}}
```
What is the correct way to use this extension ?

Sorry for being such a nooob !
Thanks

**Comment by JeroenDeDauw** [comment]
Not supported. Would need some code changes in the extension. Relevant places:

* https://github.com/JeroenDeDauw/GitHub/blob/master/src/GitHubFetcher.php#L49-L57
* https://github.com/JeroenDeDauw/GitHub/blob/master/src/Setup.php#L30

**Comment by cavepopo** [comment]
Thanks a lot for your answer, closing this issue then.
